years = [2022, 2021, 2020]

teams = [
    "UTA",
    "OKC",
    "SAC",
    "CHI",
    "GSW",
    "CHA",
    "MIN",
    "SAS",
    "LAL",
    "DAL",
    "POR",
    "MIL",
    "PHO",
    "MEM",
    "MIA",
    "DEN",
    "PHI",
    "IND",
    "ORL",
    "HOU",
    "LAC",
    "NOH",
    "WAS",
    "BOS",
    "TOR",
    "NJN",
    "ATL",
    "DET",
    "NYK",
    "CLE"
]

http_delay = 1.5

[requests.basic]
url = "https://www.basketball-reference.com/teams/TEAM_TO_CHANGE/YEAR_TO_CHANGE/gamelog/#tgl_basic"
stats = [ "FG%", "TOV" ]

[requests.advanced]
url = "https://www.basketball-reference.com/teams/TEAM_TO_CHANGE/YEAR_TO_CHANGE/gamelog-advanced/#tgl_advanced"
stats = [ "ORtg", "3PAr", "Pace" ]
